### ISSUE TITLE
Fails to compile on beta rustc 1.12.0-beta.1 (822166b84 2016-08-16)

### ISSUE THREAD

**Issue by kbknapp** [contain-rs/vec-map#20]
Error:

```
error[E0308]: mismatched types
   --> [...] /.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.6.0/src/lib.rs:952:84
    |
952 |     fn into_iter_covariant<'a, T>(iter: IntoIter<&'static T>) -> IntoIter<&'a T> { iter }
    |                                                                                    ^^^^ lifetime mismatch
    |
    = note: expected type `IntoIter<&'a T>`
    = note:    found type `IntoIter<&'static T>`
note: the lifetime 'a as defined on the block at 952:81...
   --> [...] /.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.6.0/src/lib.rs:952:82
    |
952 |     fn into_iter_covariant<'a, T>(iter: IntoIter<&'static T>) -> IntoIter<&'a T> { iter }
    |                                                                                  ^^^^^^^^
    = note: ...does not necessarily outlive the static lifetime

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `vec_map`.

To learn more, run the command again with --verbose.

```

**Comment by messense** [comment]
Same issue.

**Comment by apasel422** [comment]
Duplicate of #18 and #19.
